### PR TITLE
feature: reachable traverser

### PR DESCRIPTION
**Pull request by szikoramarci**
I would like to user the repository for my hobby project and I really need this functionality. I also want to implement a built in path finder in a grid with obstacles.

I implented that functionality. Getting a grid with hexas what you can reach from a hex when there are obstacles.
https://www.redblobgames.com/grids/hexagons/#range-obstacles

Unit tests are working fine. I would add documentation also if you think it is a useful feature.

### CODE REVIEW

**Comment by flauwekeul** [comment]
Hi. Thanks for opening a PR. The code is clean and understandable 👍

`examples/line-of-sight/index.ts` implements the required functionality but in a very different way. The beef of it is in the `fieldOfView` and `lineOfSight` traversers. `fieldOfView` is a traverser that composes the built-in `repeatWith` traverser with the custom `lineOfSight` traverser. Together they do the same thing as your implementation: start at a hex and traverse in expanding rings outward, but once an "obstacle" is reached, that hex and any hexes beyond it (from the "line of sight" of the start hex) are permanently ignored.

I think it's justified to add this "field of view" / "reachable" functionality as a standalone traverser. I'll try to make time to do these things in the coming weeks:

* Investigate which implementation is the most performant
* Think about a good name
* Think about any edge cases you (and I) haven't thought about yet
* Instead of passing a collection of "obstacles", I think it's better to pass a predicate function. This is more generic.

**Comment by szikoramarci** [comment]
Hey! Thanks for your feedback!

This "reachable" and the "field of view" functionalities are not the same. This algorythm returns a list of hexes which can be reached from the start hex if we have an exact count of steps. In that case a hex beyond an "obstacle" could be in the result list if it is reachable from start within specific steps count.

So it is not a classic hex distance feature because it should be avoid obstacles and going around.

Some context: I would like to use it for a hexagon based game when the tokens have specific moving points and should bypass each other.

In that case I think the "reachable" is better name that you firsth thought. But let me know that. Of course I'm ready to have another, better name.

Predicate function is a good idea. Can you show an example in that codebase or anywhere else? I can't imagine how that works in that situation well.

**Comment by flauwekeul** [comment]
Right, I see how it's a different traverser.

I've been thinking and I'm not so sure I see the point of adding this to the library. It seems a rather specific traverser (as is the lineOfSight traverser, that I also didn't add to the library). Why do you want to add it to Honeycomb?

**Comment by szikoramarci** [comment]
Yeah. You are right. If lineOfSight is not part of the core functionality then this function is not supposed to be either.

It gets clearer to me you really want to have only the basics and not have too specific features. Acceptable and respectable approach.

I can use this function in my branch separately from Honeycomb so it is unnecessary to have that just for me. Otherwise, it is ready-to-use so maybe we can put it into the Examples. Of course with a good, meaningful naming. :) What do you think?

**Comment by flauwekeul** [comment]
Yes, let's do that. Do you want to make a new PR with the example? I think `reachable` is a fine name. Maybe explain in its description how it's different from `lineOfSight`?

**Comment by szikoramarci** [comment]
Fine! Thanks!

I've closed that PR and I opened a new one with a description of the purpose of the reachable example.

**Pull request closed without merging**
